### ISSUE TITLE
Export song loop or full

### ISSUE THREAD

**Issue by teotigraphix** [teotigraphix/CausticSDK#45]
Currently there is the comand;

`/caustic/sequencer/export_song [path] [type] [quality]`

This exports the WAV but has not samples.

Is there a command to specify the whole song or from loop points? It would be nice to differentiate from these two options.

**Comment by teotigraphix** [comment]
Also, if I can export a loop, could their be an option for "no tail" so the loop is an exact looping samle to be loaded back into the PCMSynth or Beatbox.

I would turn all effects off and export dry when doing this.

**Comment by causticrej** [comment]
Looking at the handler for this one, it looks like IF you have loop points set, it will only export the loop (and without the tail) so knowing the song start/end beats (not sure you have an easy way of knowing the last beat though), you could get everything requested already.

**Comment by teotigraphix** [comment]
Ok this dosn't seem to work;

```
/caustic/blankrack
/caustic/load_song C:\Users\Teoti\Documents\caustic\songs\DEMO SKA.caustic
/caustic/sequencer/loop_points 0 4
/caustic/sequencer/export_song C:\Users\Teoti\Desktop\TestLoop WAV
```

The above renders out the whole 13MB wav file, not the 4 measure loop as expected.

I did test this and the sequencer is playing the song in a loop, so the points are there.

**Comment by causticrej** [comment]
Ok, two birds one stone here.

I've fix the loop export but I also changed the syntax on this one to allow for spaces in the file name (other issue). The new command is simply:

export [loop, song] [format] [quality] [path]

so let's say you want to export just a loop, set up your loop as usual then call
export loop wav 100 c:/this path has spaces

if you want the full song, use "song" instead of "loop". [quality] doesn't matter for WAV and MIDI but needs to be there, I recommend using 100 to be safe.
