### ISSUE TITLE
/caustic/save_song ${0} to use absolute path

### ISSUE THREAD

**Issue by teotigraphix** [teotigraphix/CausticSDK#63]
Same as save preset, I have to do a huge amount of copy/move.

Plus the danger of conflicts in the original presets folder.

**Comment by causticrej** [comment]
Ok, I'm going to be a bit lazy for the sake of not having to modify my code extensively for this (which means you get it quicker).

If you want to save as full path rather than automatic/relative, prefix the "name" parameter with a '@' character to indicate it's actually a full path. So for example "save_song @C:\testy" will write to "c:\testy.caustic". Omitting the @ character will behave as before.

I assume you want to leave the automatic file extension bit intact as I can't see why you'd want to change the extension types...but let me know if that's not the case and I'll treat the string as a true FULL path (you supply the extension too), that's no more work for me.

**Comment by teotigraphix** [comment]
Impl
