### ISSUE TITLE
Creating a machine with space in name does not work

### ISSUE THREAD

**Issue by teotigraphix** [teotigraphix/CausticSDK#75]

**Comment by teotigraphix** [comment]
NOTE: I cannot query a machine with a space in it either, it just gives the first part of the space split.

**Comment by causticrej** [comment]
for creation this is going to be an issue because of parameter ordering.

Example if you call: "create subsynth lead 2", did you want to create a machine called "lead 2" or one called "lead" in slot 2 ?

We can change the order the move the name to the end, but that would mean the slot number parameter now would become mandatory (it was optional before). 

OR, we remove the name parameter from the create call and rely on the "machine_name" call to do that work without ambiguity. creating a machine would give the default name until you changed it via machine_name... watcha think?

**Comment by teotigraphix** [comment]
I think for the sake of ease, we should remove the name from the call and use the slot number.

I have everything abstracted and in my framework I set the name in addMachine() anyway. So the change on my end would only take probably 30 minutes to fix stuff.

Since users can add a space In Caustic, I think this is important, my hack was replacing the space when restoring machines with a dash.
