### ISSUE TITLE
DelayEffect mode returns -1

### ISSUE THREAD

**Issue by teotigraphix** [teotigraphix/CausticSDK#83]
From your specs, it should return 1,2,3,4

**Comment by causticrej** [comment]
I can't repro this one in 3., maybe you've got an old build. I'm getting 0 1 or 2 for a mono source when testing in windows

**Comment by teotigraphix** [comment]
I just tested this with CAUSTIC STORM for machine LEAD and the first Delay effect in slot 0. I will just test creating a machine again

```
Write: /caustic/load_song C:\dev\git\sdk\CausticSDK-Tests\test-resources\songs\CAUSTIC STORM
Read: /caustic/effects_rack/1/0/mode -1000000
```

You can see it returns -1000000

**Comment by causticrej** [comment]
ok, I can see where the bug lies and why I didn't get it while testing.

I was trying to group the equivalent modes in mono and stereo but I think I re-added the mono modes even if the input is stereo.

I've taken that out so it should be 
0 = mono in, mono out
1 = X in, LR out
2 = X in, RL out
3 = stereo in, dual stereo (dual mono?) out
4 = stereo in, cross ping-pong out

**Comment by teotigraphix** [comment]
Ok, I commented on the wrong thread, I did get this to work creating a fresh synth and adding an effect.

But I couldn't get it to work loading CAUSTIC STORM and restoring the values. So this solved that issue?

**Comment by teotigraphix** [comment]
Yeah this is what I have in my code;

```
        [{label:"Mono", value:0},
        {label:"MonoLR", value:1},
        {label:"MonoRL", value:2},
        {label:"DualMono", value:3},
        {label:"PingPong", value:4}]);
```

Seems to jive with what you just wrote.
